// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_Inline ---

// CT_Inline — inline shape element
type CT_Inline struct {
	Element
}

// Extent returns the required <wp:extent> child element.
// Panics if not present (invalid XML).
func (e *CT_Inline) Extent() *CT_PositiveSize2D {
	child := e.FindChild("wp:extent")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "wp:extent", e.Tag()))
	}
	return &CT_PositiveSize2D{Element{E: child}}
}

// DocPr returns the required <wp:docPr> child element.
// Panics if not present (invalid XML).
func (e *CT_Inline) DocPr() *CT_NonVisualDrawingProps {
	child := e.FindChild("wp:docPr")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "wp:docPr", e.Tag()))
	}
	return &CT_NonVisualDrawingProps{Element{E: child}}
}

// Graphic returns the required <a:graphic> child element.
// Panics if not present (invalid XML).
func (e *CT_Inline) Graphic() *CT_GraphicalObject {
	child := e.FindChild("a:graphic")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "a:graphic", e.Tag()))
	}
	return &CT_GraphicalObject{Element{E: child}}
}

// --- CT_Anchor ---

// CT_Anchor — floating shape anchor element
type CT_Anchor struct {
	Element
}

// --- CT_Picture ---

// CT_Picture — DrawingML picture element
type CT_Picture struct {
	Element
}

// NvPicPr returns the required <pic:nvPicPr> child element.
// Panics if not present (invalid XML).
func (e *CT_Picture) NvPicPr() *CT_PictureNonVisual {
	child := e.FindChild("pic:nvPicPr")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "pic:nvPicPr", e.Tag()))
	}
	return &CT_PictureNonVisual{Element{E: child}}
}

// BlipFill returns the required <pic:blipFill> child element.
// Panics if not present (invalid XML).
func (e *CT_Picture) BlipFill() *CT_BlipFillProperties {
	child := e.FindChild("pic:blipFill")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "pic:blipFill", e.Tag()))
	}
	return &CT_BlipFillProperties{Element{E: child}}
}

// SpPr returns the required <pic:spPr> child element.
// Panics if not present (invalid XML).
func (e *CT_Picture) SpPr() *CT_ShapeProperties {
	child := e.FindChild("pic:spPr")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "pic:spPr", e.Tag()))
	}
	return &CT_ShapeProperties{Element{E: child}}
}

// --- CT_PictureNonVisual ---

// CT_PictureNonVisual — non-visual picture properties element
type CT_PictureNonVisual struct {
	Element
}

// CNvPr returns the required <pic:cNvPr> child element.
// Panics if not present (invalid XML).
func (e *CT_PictureNonVisual) CNvPr() *CT_NonVisualDrawingProps {
	child := e.FindChild("pic:cNvPr")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "pic:cNvPr", e.Tag()))
	}
	return &CT_NonVisualDrawingProps{Element{E: child}}
}

// --- CT_NonVisualDrawingProps ---

// CT_NonVisualDrawingProps — non-visual drawing properties element
type CT_NonVisualDrawingProps struct {
	Element
}

// Id returns the value of the required "id" attribute.
func (e *CT_NonVisualDrawingProps) Id() (int, error) {
	val, ok := e.GetAttr("id")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "id", e.Tag())
	}
	return parseIntAttr(val), nil
}

// SetId sets the required "id" attribute.
func (e *CT_NonVisualDrawingProps) SetId(v int) {
	e.SetAttr("id", formatIntAttr(v))
}

// Name returns the value of the required "name" attribute.
func (e *CT_NonVisualDrawingProps) Name() (string, error) {
	val, ok := e.GetAttr("name")
	if !ok {
		return "", fmt.Errorf("required attribute %q not present on <%s>", "name", e.Tag())
	}
	return val, nil
}

// SetName sets the required "name" attribute.
func (e *CT_NonVisualDrawingProps) SetName(v string) {
	e.SetAttr("name", v)
}

// --- CT_NonVisualPictureProperties ---

// CT_NonVisualPictureProperties — non-visual picture-specific properties
type CT_NonVisualPictureProperties struct {
	Element
}

// --- CT_GraphicalObject ---

// CT_GraphicalObject — graphical object element
type CT_GraphicalObject struct {
	Element
}

// GraphicData returns the required <a:graphicData> child element.
// Panics if not present (invalid XML).
func (e *CT_GraphicalObject) GraphicData() *CT_GraphicalObjectData {
	child := e.FindChild("a:graphicData")
	if child == nil {
		panic(fmt.Sprintf("required <%s> child not present in <%s>", "a:graphicData", e.Tag()))
	}
	return &CT_GraphicalObjectData{Element{E: child}}
}

// --- CT_GraphicalObjectData ---

// CT_GraphicalObjectData — graphical object data element
type CT_GraphicalObjectData struct {
	Element
}

// Pic returns the <pic:pic> child element, or nil if not present.
func (e *CT_GraphicalObjectData) Pic() *CT_Picture {
	child := e.FindChild("pic:pic")
	if child == nil {
		return nil
	}
	return &CT_Picture{Element{E: child}}
}

// GetOrAddPic returns <pic:pic>, creating it if not present.
func (e *CT_GraphicalObjectData) GetOrAddPic() *CT_Picture {
	child := e.Pic()
	if child != nil {
		return child
	}
	return e.addPic()
}

// RemovePic removes all <pic:pic> child elements.
func (e *CT_GraphicalObjectData) RemovePic() {
	e.RemoveAll("pic:pic")
}

// addPic adds a new <pic:pic> in correct sequence.
func (e *CT_GraphicalObjectData) addPic() *CT_Picture {
	child := e.newPic()
	e.insertPic(child)
	return child
}

// newPic creates a detached <pic:pic> element.
func (e *CT_GraphicalObjectData) newPic() *CT_Picture {
	el := OxmlElement("pic:pic")
	return &CT_Picture{Element{E: el}}
}

// insertPic inserts child before first successor.
func (e *CT_GraphicalObjectData) insertPic(child *CT_Picture) *CT_Picture {
	e.InsertElementBefore(child.E)
	return child
}

// Uri returns the value of the required "uri" attribute.
func (e *CT_GraphicalObjectData) Uri() (string, error) {
	val, ok := e.GetAttr("uri")
	if !ok {
		return "", fmt.Errorf("required attribute %q not present on <%s>", "uri", e.Tag())
	}
	return val, nil
}

// SetUri sets the required "uri" attribute.
func (e *CT_GraphicalObjectData) SetUri(v string) {
	e.SetAttr("uri", v)
}

// --- CT_BlipFillProperties ---

// CT_BlipFillProperties — blip fill properties element
type CT_BlipFillProperties struct {
	Element
}

// Blip returns the <a:blip> child element, or nil if not present.
func (e *CT_BlipFillProperties) Blip() *CT_Blip {
	child := e.FindChild("a:blip")
	if child == nil {
		return nil
	}
	return &CT_Blip{Element{E: child}}
}

// GetOrAddBlip returns <a:blip>, creating it if not present.
func (e *CT_BlipFillProperties) GetOrAddBlip() *CT_Blip {
	child := e.Blip()
	if child != nil {
		return child
	}
	return e.addBlip()
}

// RemoveBlip removes all <a:blip> child elements.
func (e *CT_BlipFillProperties) RemoveBlip() {
	e.RemoveAll("a:blip")
}

// addBlip adds a new <a:blip> in correct sequence.
func (e *CT_BlipFillProperties) addBlip() *CT_Blip {
	child := e.newBlip()
	e.insertBlip(child)
	return child
}

// newBlip creates a detached <a:blip> element.
func (e *CT_BlipFillProperties) newBlip() *CT_Blip {
	el := OxmlElement("a:blip")
	return &CT_Blip{Element{E: el}}
}

// insertBlip inserts child before first successor.
func (e *CT_BlipFillProperties) insertBlip(child *CT_Blip) *CT_Blip {
	e.InsertElementBefore(child.E, "a:srcRect", "a:tile", "a:stretch")
	return child
}

// --- CT_Blip ---

// CT_Blip — blip element specifying image source
type CT_Blip struct {
	Element
}

// Embed returns the value of the "r:embed" attribute, or "" if absent.
func (e *CT_Blip) Embed() string {
	val, ok := e.GetAttr("r:embed")
	if !ok {
		return ""
	}
	return val
}

// SetEmbed sets the "r:embed" attribute.
// Passing "" removes it.
func (e *CT_Blip) SetEmbed(v string) {
	if v == "" {
		e.RemoveAttr("r:embed")
		return
	}
	e.SetAttr("r:embed", v)
}

// Link returns the value of the "r:link" attribute, or "" if absent.
func (e *CT_Blip) Link() string {
	val, ok := e.GetAttr("r:link")
	if !ok {
		return ""
	}
	return val
}

// SetLink sets the "r:link" attribute.
// Passing "" removes it.
func (e *CT_Blip) SetLink(v string) {
	if v == "" {
		e.RemoveAttr("r:link")
		return
	}
	e.SetAttr("r:link", v)
}

// --- CT_ShapeProperties ---

// CT_ShapeProperties — shape properties element
type CT_ShapeProperties struct {
	Element
}

// Xfrm returns the <a:xfrm> child element, or nil if not present.
func (e *CT_ShapeProperties) Xfrm() *CT_Transform2D {
	child := e.FindChild("a:xfrm")
	if child == nil {
		return nil
	}
	return &CT_Transform2D{Element{E: child}}
}

// GetOrAddXfrm returns <a:xfrm>, creating it if not present.
func (e *CT_ShapeProperties) GetOrAddXfrm() *CT_Transform2D {
	child := e.Xfrm()
	if child != nil {
		return child
	}
	return e.addXfrm()
}

// RemoveXfrm removes all <a:xfrm> child elements.
func (e *CT_ShapeProperties) RemoveXfrm() {
	e.RemoveAll("a:xfrm")
}

// addXfrm adds a new <a:xfrm> in correct sequence.
func (e *CT_ShapeProperties) addXfrm() *CT_Transform2D {
	child := e.newXfrm()
	e.insertXfrm(child)
	return child
}

// newXfrm creates a detached <a:xfrm> element.
func (e *CT_ShapeProperties) newXfrm() *CT_Transform2D {
	el := OxmlElement("a:xfrm")
	return &CT_Transform2D{Element{E: el}}
}

// insertXfrm inserts child before first successor.
func (e *CT_ShapeProperties) insertXfrm(child *CT_Transform2D) *CT_Transform2D {
	e.InsertElementBefore(child.E, "a:custGeom", "a:prstGeom", "a:ln", "a:effectLst", "a:effectDag", "a:scene3d", "a:sp3d", "a:extLst")
	return child
}

// --- CT_Transform2D ---

// CT_Transform2D — 2D transform element
type CT_Transform2D struct {
	Element
}

// Off returns the <a:off> child element, or nil if not present.
func (e *CT_Transform2D) Off() *CT_Point2D {
	child := e.FindChild("a:off")
	if child == nil {
		return nil
	}
	return &CT_Point2D{Element{E: child}}
}

// GetOrAddOff returns <a:off>, creating it if not present.
func (e *CT_Transform2D) GetOrAddOff() *CT_Point2D {
	child := e.Off()
	if child != nil {
		return child
	}
	return e.addOff()
}

// RemoveOff removes all <a:off> child elements.
func (e *CT_Transform2D) RemoveOff() {
	e.RemoveAll("a:off")
}

// addOff adds a new <a:off> in correct sequence.
func (e *CT_Transform2D) addOff() *CT_Point2D {
	child := e.newOff()
	e.insertOff(child)
	return child
}

// newOff creates a detached <a:off> element.
func (e *CT_Transform2D) newOff() *CT_Point2D {
	el := OxmlElement("a:off")
	return &CT_Point2D{Element{E: el}}
}

// insertOff inserts child before first successor.
func (e *CT_Transform2D) insertOff(child *CT_Point2D) *CT_Point2D {
	e.InsertElementBefore(child.E, "a:ext")
	return child
}

// Ext returns the <a:ext> child element, or nil if not present.
func (e *CT_Transform2D) Ext() *CT_PositiveSize2D {
	child := e.FindChild("a:ext")
	if child == nil {
		return nil
	}
	return &CT_PositiveSize2D{Element{E: child}}
}

// GetOrAddExt returns <a:ext>, creating it if not present.
func (e *CT_Transform2D) GetOrAddExt() *CT_PositiveSize2D {
	child := e.Ext()
	if child != nil {
		return child
	}
	return e.addExt()
}

// RemoveExt removes all <a:ext> child elements.
func (e *CT_Transform2D) RemoveExt() {
	e.RemoveAll("a:ext")
}

// addExt adds a new <a:ext> in correct sequence.
func (e *CT_Transform2D) addExt() *CT_PositiveSize2D {
	child := e.newExt()
	e.insertExt(child)
	return child
}

// newExt creates a detached <a:ext> element.
func (e *CT_Transform2D) newExt() *CT_PositiveSize2D {
	el := OxmlElement("a:ext")
	return &CT_PositiveSize2D{Element{E: el}}
}

// insertExt inserts child before first successor.
func (e *CT_Transform2D) insertExt(child *CT_PositiveSize2D) *CT_PositiveSize2D {
	e.InsertElementBefore(child.E)
	return child
}

// --- CT_PositiveSize2D ---

// CT_PositiveSize2D — positive size 2D element
type CT_PositiveSize2D struct {
	Element
}

// Cx returns the value of the required "cx" attribute.
func (e *CT_PositiveSize2D) Cx() (int64, error) {
	val, ok := e.GetAttr("cx")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "cx", e.Tag())
	}
	return parseInt64Attr(val), nil
}

// SetCx sets the required "cx" attribute.
func (e *CT_PositiveSize2D) SetCx(v int64) {
	e.SetAttr("cx", formatInt64Attr(v))
}

// Cy returns the value of the required "cy" attribute.
func (e *CT_PositiveSize2D) Cy() (int64, error) {
	val, ok := e.GetAttr("cy")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "cy", e.Tag())
	}
	return parseInt64Attr(val), nil
}

// SetCy sets the required "cy" attribute.
func (e *CT_PositiveSize2D) SetCy(v int64) {
	e.SetAttr("cy", formatInt64Attr(v))
}

// --- CT_Point2D ---

// CT_Point2D — point 2D element
type CT_Point2D struct {
	Element
}

// X returns the value of the required "x" attribute.
func (e *CT_Point2D) X() (int64, error) {
	val, ok := e.GetAttr("x")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "x", e.Tag())
	}
	return parseInt64Attr(val), nil
}

// SetX sets the required "x" attribute.
func (e *CT_Point2D) SetX(v int64) {
	e.SetAttr("x", formatInt64Attr(v))
}

// Y returns the value of the required "y" attribute.
func (e *CT_Point2D) Y() (int64, error) {
	val, ok := e.GetAttr("y")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "y", e.Tag())
	}
	return parseInt64Attr(val), nil
}

// SetY sets the required "y" attribute.
func (e *CT_Point2D) SetY(v int64) {
	e.SetAttr("y", formatInt64Attr(v))
}

// --- CT_PresetGeometry2D ---

// CT_PresetGeometry2D — preset geometry element
type CT_PresetGeometry2D struct {
	Element
}

// --- CT_RelativeRect ---

// CT_RelativeRect — relative rect element
type CT_RelativeRect struct {
	Element
}

// --- CT_StretchInfoProperties ---

// CT_StretchInfoProperties — stretch info properties
type CT_StretchInfoProperties struct {
	Element
}
