// Code generated by codegen; DO NOT EDIT.

package oxml

import (
	"fmt"
)

// Ensure imports are used.
var _ = fmt.Sprintf

// --- CT_DecimalNumber ---

// CT_DecimalNumber — decimal number element used for w:numId, w:ilvl, w:abstractNumId, w:gridSpan, etc.
type CT_DecimalNumber struct {
	Element
}

// Val returns the value of the required "w:val" attribute.
func (e *CT_DecimalNumber) Val() (int, error) {
	val, ok := e.GetAttr("w:val")
	if !ok {
		return 0, fmt.Errorf("required attribute %q not present on <%s>", "w:val", e.Tag())
	}
	return parseIntAttr(val), nil
}

// SetVal sets the required "w:val" attribute.
func (e *CT_DecimalNumber) SetVal(v int) {
	e.SetAttr("w:val", formatIntAttr(v))
}

// --- CT_OnOff ---

// CT_OnOff — on/off element used for w:b, w:i, w:caps, etc. Defaults to true.
type CT_OnOff struct {
	Element
}

// Val returns the value of the "w:val" attribute, or true if absent.
func (e *CT_OnOff) Val() bool {
	val, ok := e.GetAttr("w:val")
	if !ok {
		return true
	}
	return parseBoolAttr(val)
}

// SetVal sets the "w:val" attribute.
// Passing true removes it.
func (e *CT_OnOff) SetVal(v bool) {
	if v == true {
		e.RemoveAttr("w:val")
		return
	}
	e.SetAttr("w:val", formatBoolAttr(v))
}

// --- CT_String ---

// CT_String — string element used for w:pStyle, w:tblStyle, w:rStyle, etc.
type CT_String struct {
	Element
}

// Val returns the value of the required "w:val" attribute.
func (e *CT_String) Val() (string, error) {
	val, ok := e.GetAttr("w:val")
	if !ok {
		return "", fmt.Errorf("required attribute %q not present on <%s>", "w:val", e.Tag())
	}
	return val, nil
}

// SetVal sets the required "w:val" attribute.
func (e *CT_String) SetVal(v string) {
	e.SetAttr("w:val", v)
}
